### ISSUE TITLE
Optimize CSS

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-tips#104]
Three possible improvements:

* Minify at build-time.
* Split into two main css files: lists of tips, content of a tip. These things aren't displayed at the same time, but we're always loading everything on all pages.
* Removed unused CSS. There's probably some of it somewhere, like
  ```css
  .tips .tip.highlighted .highlight {
    background: var(--accent-color);
  }
  .tips.searching .tip:not(.highlighted) {
    display: none;
  }
  ```
